### ISSUE TITLE
How I do get the log of not unique devices?

### ISSUE THREAD

**Issue by ghost** [MS3FGX/Bluelog#10]
When I turn on and off in several times my smartphone during the Bluelog console time, the Bluelog just detect one time (first one). I want to make the log for the several times with timestamp. 

Additionally, I want to get the raw data of the bluetooth packets. Is it possible to do these using the Bluelog?

**Comment by MS3FGX** [comment]
So you probably figured it out, but the -a option will make Bluelog "forget" devices and should do what you want.

As for the raw packets, unfortunately that's something happening on a different level from where Bluelog works.

**Comment by ghost** [comment]
> So you probably figured it out, but the -a option will make Bluelog "forget" devices and should do what you want.
> 
> As for the raw packets, unfortunately that's something happening on a different level from where Bluelog works.

Thanks to your comments. I didn't understand the "forget". Ah, can I ask one question about Bluetooth? Actually, I would like to analyze wireless signals (Wi-Fi and Bluetooth for human mobility. I set my Wi-Fi scanner and now try to make the Bluetooth sensor now. However, the Bluetooth can be detected when I just turn on the Bluetooth function in my smartphone or earphone. I thought the devices emit Bluetooth signal periodically and regularly such like Wi-Fi. Is it not the similar with the Wi-Fi? I'm so sorry to ask different question.

**Comment by MS3FGX** [comment]
Modern devices only go into Discovery mode when you're actively looking for another BT device or pairing it. So you'll pick up far fewer devices with a tool like Bluelog now than you would when it was first developed.
