### ISSUE TITLE
Feature request: Command-line argument for custom log file field delimiter

### ISSUE THREAD

**Issue by NHMatt** [MS3FGX/Bluelog#3]
I noticed that some user friend manufacturer names contain a comma.  I plan to write a quick and dirty java parser to persist my logs into a database.  I was hoping you might consider adding a command line argument to allow a customer delimiter character (such as a pipe, a tab, etc).  One that will not (or at least is less likely to) cause parse errors.

Thanks!

**Comment by MS3FGX** [comment]
If anyone still has a need for custom delimiters let me know, but I think this fix was probably enough to get the job done.
